Chess move validation
njit-cs-490-002-spring23/group-project-group-7y pull request #15
Opened 2023-12-06 14:12 UTC by RaymondRLopez

Movement validations for the pieces.

2023-12-08 18:54 UTC, sivaanand13 requested changes
I mostly only have style comments which have been commented in the code. The test for nextBestMove fails so don't merge until it's fixed.

2023-12-08 19:29 UTC, RaymondRLopez commented on townService/src/town/games/ChessGame.ts
> +      this.state.black = undefined;
I deleted the unnecessary line.

2023-12-08 23:23 UTC, sivaanand13 approved these changes

2023-12-12 20:47 UTC, sivaanand13 commented
Looks good.

2023-12-12 20:47 UTC, sivaanand13 approved these changes

2023-12-12 21:24 UTC, merged